import boto3 

dynamodb = boto3.resource('dynamodb')
table = dynamodb.Table('CloudDefinitions')


definitions = [
    {"id": "1", "definition": "Cloud computing is the delivery of computing services over the internet."},
    {"id": "2", "definition": "Infrastructure as a Service (IaaS) provides virtualized computing resources over the internet."},
    {"id": "3", "definition": "Platform as a Service (PaaS) allows customers to develop, run, and manage applications without dealing with infrastructure."},
    {"id": "4", "definition": "Software as a Service (SaaS) delivers software applications over the internet on a subscription basis."},
    {"id": "5", "definition": "Public cloud is a cloud computing model where services are shared across multiple organizations."},
    {"id": "6", "definition": "Private cloud is a cloud computing model dedicated to a single organization, enhancing security and control."},
    {"id": "7", "definition": "Hybrid cloud combines public and private clouds, allowing data and applications to be shared between them."},
    {"id": "8", "definition": "Multi-cloud refers to the use of multiple cloud computing services from different providers in a single architecture."},
    {"id": "9", "definition": "Cloud storage enables data to be stored on remote servers accessed via the internet."},
    {"id": "10", "definition": "Virtual Machine (VM) is a software emulation of physical computers that allows multiple OS instances to run on a single machine."},
    {"id": "11", "definition": "Containerization encapsulates an application and its dependencies into a single unit called a container."},
    {"id": "12", "definition": "Microservices is an architectural style that structures an application as a collection of small, independent services."},
    {"id": "13", "definition": "Serverless computing allows developers to build and run applications without managing servers."},
    {"id": "14", "definition": "DevOps is a set of practices that combines software development (Dev) and IT operations (Ops) for improved collaboration."},
    {"id": "15", "definition": "Cloud-native applications are designed to leverage cloud computing architectures and services."},
    {"id": "16", "definition": "Cloud orchestration automates the management of complex cloud services and workflows."},
    {"id": "17", "definition": "Cloud migration is the process of moving data, applications, and workloads to a cloud environment."},
    {"id": "18", "definition": "API (Application Programming Interface) allows applications to communicate with each other over the internet."},
    {"id": "19", "definition": "Data center is a facility used to house computer systems and associated components, such as telecommunications and storage."},
    {"id": "20", "definition": "Edge computing processes data closer to the source to reduce latency and bandwidth usage."},
    {"id": "21", "definition": "Load balancing distributes incoming network traffic across multiple servers to ensure reliability and performance."},
    {"id": "22", "definition": "Cloud security encompasses the technologies, policies, and controls that protect data, applications, and infrastructure."},
    {"id": "23", "definition": "Backup as a Service (BaaS) provides data backup and recovery solutions over the cloud."},
    {"id": "24", "definition": "Disaster Recovery as a Service (DRaaS) provides backup resources and failover to protect against data loss."},
    {"id": "25", "definition": "Data lake is a centralized repository that allows you to store structured and unstructured data at any scale."},
    {"id": "26", "definition": "Data warehouse is a system used for reporting and data analysis, centralizing data from different sources."},
    {"id": "27", "definition": "Big data refers to extremely large datasets that require advanced tools and technologies to analyze."},
    {"id": "28", "definition": "Analytics as a Service (AaaS) provides analytics tools and technologies through the cloud."},
    {"id": "29", "definition": "Cloud governance is the framework for managing cloud services and resources to ensure compliance and security."},
    {"id": "30", "definition": "Cloud cost management involves monitoring, optimizing, and controlling cloud expenses."},
    {"id": "31", "definition": "Service Level Agreement (SLA) is a contract that defines the level of service expected from a service provider."},
    {"id": "32", "definition": "Virtual Private Cloud (VPC) is a private cloud hosted within a public cloud environment."},
    {"id": "33", "definition": "Cloud API provides a way for applications to interact with cloud services programmatically."},
    {"id": "34", "definition": "Cloud broker acts as an intermediary between cloud service providers and consumers."},
    {"id": "35", "definition": "Cloud service model defines the type of cloud service provided (IaaS, PaaS, SaaS)."},
    {"id": "36", "definition": "Scaling refers to the ability to adjust resources based on demand."},
    {"id": "37", "definition": "Auto-scaling automatically adjusts the number of active servers based on load."},
    {"id": "38", "definition": "Cloud provisioning is the process of allocating cloud resources to users."},
    {"id": "39", "definition": "Identity and Access Management (IAM) allows organizations to manage access to cloud resources."},
    {"id": "40", "definition": "Cloud resource tagging allows for better management and organization of cloud resources."},
    {"id": "41", "definition": "Continuous Integration (CI) is a software development practice where code changes are automatically tested."},
    {"id": "42", "definition": "Continuous Deployment (CD) automates the release of new software versions to production."},
    {"id": "43", "definition": "Monitoring in cloud computing involves tracking the performance and availability of services."},
    {"id": "44", "definition": "Logging collects and stores log data for auditing and troubleshooting purposes."},
    {"id": "45", "definition": "Data encryption protects data by converting it into a secure format."},
    {"id": "46", "definition": "Multi-tenancy allows multiple users to share the same cloud resources securely."},
    {"id": "47", "definition": "Cloud integration connects different cloud services and applications to work together."},
    {"id": "48", "definition": "Serverless architecture allows developers to build applications without managing servers."},
    {"id": "49", "definition": "Kubernetes is an open-source container orchestration platform for automating deployment."},
    {"id": "50", "definition": "Cloud-based development environments allow developers to code in the cloud."},
    {"id": "51", "definition": "Content Delivery Network (CDN) distributes content to users based on their geographic location."},
    {"id": "52", "definition": "Elasticity in cloud computing refers to the ability to dynamically allocate and release resources."},
    {"id": "53", "definition": "Serverless functions are pieces of code that run in response to events without server management."},
    {"id": "54", "definition": "Data governance ensures data accuracy, availability, and usability in cloud environments."},
    {"id": "55", "definition": "Data lifecycle management defines the policies for managing data throughout its lifecycle."},
    {"id": "56", "definition": "Virtual Desktop Infrastructure (VDI) allows users to access a desktop operating system hosted on a server."},
    {"id": "57", "definition": "Cloud compliance ensures that cloud services meet legal and regulatory requirements."},
    {"id": "58", "definition": "Service Mesh is a dedicated infrastructure layer for handling service-to-service communication."},
    {"id": "59", "definition": "API Gateway manages and routes API requests between clients and backend services."},
    {"id": "60", "definition": "Data residency refers to the physical or geographic location of data."},
    {"id": "61", "definition": "Cloud-native storage is designed to support cloud computing architectures and environments."},
    {"id": "62", "definition": "Platform as a Service (PaaS) provides a framework for developers to build upon."},
    {"id": "63", "definition": "Cloud adoption is the process of transitioning to cloud services."},
    {"id": "64", "definition": "Microservices architecture is an approach to developing software applications as a suite of independently deployable services."},
    {"id": "65", "definition": "Container orchestration automates the deployment, management, and scaling of containerized applications."},
    {"id": "66", "definition": "Cloud engineering involves designing, building, and managing cloud-based systems."},
    {"id": "67", "definition": "Cloud management platforms provide tools for managing cloud services and resources."},
    {"id": "68", "definition": "Artificial Intelligence (AI) in the cloud provides AI capabilities through cloud services."},
    {"id": "69", "definition": "Machine Learning (ML) in the cloud offers machine learning capabilities and tools in cloud environments."},
    {"id": "70", "definition": "Data replication involves copying data from one location to another for backup and redundancy."},
    {"id": "71", "definition": "Data transformation alters data to fit operational needs or analysis."},
    {"id": "72", "definition": "Network virtualization abstracts network resources for improved scalability and efficiency."},
    {"id": "73", "definition": "Cloud elasticity automatically scales resources up or down based on demand."},
    {"id": "74", "definition": "User-defined function (UDF) is a function that users create to extend database capabilities."},
    {"id": "75", "definition": "Serverless architecture allows for the execution of code without managing server infrastructure."},
    {"id": "76", "definition": "Cloud provider is a company that offers cloud services to individuals or organizations."},
    {"id": "77", "definition": "Resource allocation assigns cloud resources to specific applications or users."},
    {"id": "78", "definition": "Cloud application is a software program that is hosted in the cloud."},
    {"id": "79", "definition": "Infrastructure management involves overseeing cloud infrastructure and services."},
    {"id": "80", "definition": "Disaster recovery is the process of restoring IT operations after a disruptive event."},
    {"id": "81", "definition": "Cloud workflow automates processes and tasks across cloud services."},
    {"id": "82", "definition": "Data mining is the practice of examining large datasets to discover patterns and insights."},
    {"id": "83", "definition": "Cloud-native database is designed to operate in cloud environments."},
    {"id": "84", "definition": "Cloud application architecture defines how cloud applications are built and deployed."},
    {"id": "85", "definition": "Performance monitoring tracks the performance metrics of cloud services."},
    {"id": "86", "definition": "Data archiving is the process of moving data that is no longer actively used to a separate storage location."},
    {"id": "87", "definition": "Data visualization tools help users understand data through visual representations."},
    {"id": "88", "definition": "Big Data analytics involves analyzing large and complex datasets to uncover hidden patterns."},
    {"id": "89", "definition": "A/B testing compares two versions of a web page or app to determine which one performs better."},
    {"id": "90", "definition": "Cloud-native security focuses on securing cloud applications and services."},
    {"id": "91", "definition": "Cloud resource management involves managing and optimizing cloud resources."},
    {"id": "92", "definition": "Identity federation allows users to authenticate with multiple systems using one identity."},
    {"id": "93", "definition": "Security Information and Event Management (SIEM) collects and analyzes security data in real-time."},
    {"id": "94", "definition": "Cloud firewall protects cloud resources by controlling traffic."},
    {"id": "95", "definition": "Cloud analytics provides insights from data stored in the cloud."},
    {"id": "96", "definition": "Service discovery allows services to find and communicate with each other."},
    {"id": "97", "definition": "Data integrity ensures the accuracy and consistency of data over its lifecycle."},
    {"id": "98", "definition": "Rate limiting restricts the number of requests a user can make to a service."},
    {"id": "99", "definition": "Configuration management involves maintaining computer systems and software in a desired, consistent state."},
    {"id": "100", "definition": "DevSecOps integrates security practices into the DevOps process."}
]


def insert_definitions():
    for definition in definitions:
        table.put_item(Item=definition)
    print("Definitions inserted!")


insert_definitions()